server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: test
    jedis:
      pool: #连接池配置
        max-active: 8 #最大活跃连接数，默认8个。
        max-idle: 8 #最大空闲连接数，默认8个。
        max-wait: -1 #获取连接的最大等待时间，默认-1，表示无限制，单位毫秒。默认值可能会因为获取不到连接，导致事务无法提交，数据库被锁，大量线程处于等待状态的情况。
        min-idle: 0 #最小空闲连接数，默认0。
  devtools:
    restart:
      enabled: true
